Repository pagopa/pagopa-fdr, pull requests merged in 2023-09, with the labels that each got.

#38 feat: NOD-211 fix re
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/rest/support/SupportResource.java
  src/main/java/it/gov/pagopa/fdr/rest/support/mapper/SupportResourceServiceMapper.java
  src/main/java/it/gov/pagopa/fdr/rest/support/response/FdrByIurResponse.java
  src/main/java/it/gov/pagopa/fdr/rest/support/response/FdrByIuvResponse.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
  src/main/java/it/gov/pagopa/fdr/service/re/model/ReAbstract.java
  src/main/java/it/gov/pagopa/fdr/service/support/SupportService.java
  src/main/java/it/gov/pagopa/fdr/service/support/mapper/SupportServiceServiceMapper.java
  src/main/java/it/gov/pagopa/fdr/util/MDCKeys.java
Labels: size/small

#39 feat: NOD-211 fix re
  src/main/java/it/gov/pagopa/fdr/rest/filter/RequestFilter.java
  src/main/java/it/gov/pagopa/fdr/rest/filter/ResponseFilter.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
Labels: size/small

#37 feat: [NOD-368] new Unit tests for ReService
  .quarkus/cli/plugins/quarkus-cli-catalog.json
  pom.xml
  src/main/java/it/gov/pagopa/fdr/service/re/ReService.java
  src/test/java/it/gov/pagopa/fdr/service/re/ReServiceTest.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: enhancement

#36 feat: Fix iuv iur base class and added tests
  .quarkus/cli/plugins/quarkus-cli-catalog.json
  openapi/openapi.json
  openapi/openapi_internal.json
  pom.xml
  postman-collection/fdr.postman_collection.json
  src/main/java/it/gov/pagopa/fdr/rest/model/FdrByPspIdIuvIurBase.java
  src/main/java/it/gov/pagopa/fdr/rest/support/SupportResource.java
  src/main/java/it/gov/pagopa/fdr/rest/support/mapper/SupportResourceServiceMapper.java
  src/main/java/it/gov/pagopa/fdr/rest/support/response/FdrByIur.java
  src/main/java/it/gov/pagopa/fdr/rest/support/response/FdrByIuvResponse.java
  src/main/java/it/gov/pagopa/fdr/rest/support/response/FdrByPspIdIuvIurResponse.java
  src/main/java/it/gov/pagopa/fdr/service/re/ReService.java
  src/test/java/it/gov/pagopa/fdr/rest/support/SupportTest.java
  src/test/java/it/gov/pagopa/fdr/service/re/ReServiceTest.java
Labels: enhancement, size/large, minor
