Repository pagopa/pagopa-fdr, pull requests merged in 2023-10, with the labels that each got.

#42 [NOD-490] feat: updated to standard existing GitHub Actions
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .github/workflows/00_add_patch_label.yml
  .github/workflows/01_anchore.yml
  .github/workflows/01_assignee.yml
  .github/workflows/02_check_pr.yml
  .github/workflows/03_code_review.yml
  .github/workflows/04_release_and_deploy.yml
  .github/workflows/04h_deploy_with_github_runner.yml
  .github/workflows/05_update_code.yml
  .github/workflows/check_pr.yml
  .github/workflows/update_code.yml
  .github/workflows/update_infra.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/README.md
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
Labels: size/large, ignore-for-release

#43 fix: refactored wrong pipelines
  .github/workflows/01_anchore.yml
  .github/workflows/04_release_and_deploy.yml
Labels: size/small, ignore-for-release

#44 fix: resolved errors on deploy pipeline
  .github/workflows/04h_deploy_with_github_runner.yml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, ignore-for-release

#45 fix: resolved wrong deployment with related GH pipeline
  .github/workflows/04_release_and_deploy.yml
  .gitignore
  .identity/.terraform.lock.hcl
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  helm/weu-dev/values-dev.yaml
  helm/weu-uat/values-uat.yaml
Labels: ignore-for-release

#46 NOD-545 - fix revision
  pom.xml
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
Labels: size/small, patch

#47 NOD-545
  helm/values-dev.yaml
  helm/values-uat.yaml
  pom.xml
Labels: size/small, patch

#48 added int test pipeline
  .github/workflows/06_integration_test.yml
Labels: ignore-for-release
