Repository pagopa/pagopa-fdr, pull requests merged in 2023-11, with the labels that each got.

#51 Integration test fix
  integration-test/features/add_revision_case.feature
  integration-test/features/check_pageable_org_case.feature
  integration-test/features/check_pageable_psp_case.feature
  integration-test/features/delete_created_fdr_case.feature
  integration-test/features/organization_happy_case.feature
  integration-test/features/psp_check_fdr_published_case.feature
  integration-test/steps/steps.py
  integration-test/steps/utils.py
Labels: size/small, ignore-for-release

#41 feat: NOD-513 adeguamento log per creazione dashboard kibana
  src/main/java/it/gov/pagopa/fdr/rest/exceptionmapper/ExceptionMappers.java
  src/main/java/it/gov/pagopa/fdr/rest/filter/RequestFilter.java
  src/main/java/it/gov/pagopa/fdr/rest/filter/ResponseFilter.java
  src/main/java/it/gov/pagopa/fdr/rest/organizations/BaseOrganizationsResource.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/BasePspResource.java
  src/main/java/it/gov/pagopa/fdr/rest/support/SupportResource.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/OrganizationsService.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
  src/main/java/it/gov/pagopa/fdr/service/support/SupportService.java
  src/main/java/it/gov/pagopa/fdr/util/AppConstant.java
  src/main/java/it/gov/pagopa/fdr/util/MDCKeys.java
Labels: patch

#52 [NOD-589] feat: Performance test
  .github/workflows/07_performance_test.yml
  performance-test/docker-compose.yaml
  performance-test/run_performance_test.sh
  performance-test/src/config.json
  performance-test/src/dev.environment.json
  performance-test/src/happy_case_scenario.js
  performance-test/src/helpers/fdr_helper.js
  performance-test/src/helpers/payloads.json
  performance-test/src/main_scanario.js
  performance-test/src/test-types/ramping.json
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/projection/FdrPublishByPspProjection.java
  src/main/java/it/gov/pagopa/fdr/rest/exceptionmapper/ExceptionMappers.java
  src/main/java/it/gov/pagopa/fdr/rest/filter/RequestFilter.java
  src/main/java/it/gov/pagopa/fdr/rest/filter/ResponseFilter.java
  src/main/java/it/gov/pagopa/fdr/rest/model/FdrPublished.java
  src/main/java/it/gov/pagopa/fdr/rest/organizations/BaseOrganizationsResource.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/BasePspResource.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/InternalPspsResource.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/PspsResource.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/response/GetAllPublishedResponse.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/validation/PspsValidationService.java
  src/main/java/it/gov/pagopa/fdr/service/dto/FdrAllPublishedDto.java
  src/main/java/it/gov/pagopa/fdr/service/dto/FdrSimplePublishedDto.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/OrganizationsService.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
  src/main/java/it/gov/pagopa/fdr/service/psps/mapper/PspsServiceServiceMapper.java
  src/test/java/it/gov/pagopa/fdr/rest/psps/InternalPspResourceTest.java
  src/test/java/it/gov/pagopa/fdr/rest/support/SupportTest.java
Labels: size/large, patch
