Repository pagopa/pagopa-fdr, pull requests merged in 2023-05, with the labels that each got.

#7 mock cache
  docker-infra/docker-compose.yml
  docker-infra/mock/data/config.json
  docker-infra/mock/data/id.json
  docker-infra/mock/nginx/nginx.conf
  src/main/java/it/gov/pagopa/fdr/Config.java
  src/main/openapi/api_config_cache.json
  src/main/resources/application.properties
Labels: size/large

#9 feat: Fix test
  src/main/resources/application.properties
Labels: size/small

#12 feat: Sonar fix
  src/main/java/it/gov/pagopa/fdr/App.java
  src/main/java/it/gov/pagopa/fdr/AppStartup.java
  src/main/java/it/gov/pagopa/fdr/Config.java
  src/main/java/it/gov/pagopa/fdr/exception/AppException.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrHistoryEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentHistoryEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/AbstractReportingFlowEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/AbstractReportingFlowPaymentEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/PaymentStatusEnumEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/ReceiverEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/ReportingFlowStatusEnumEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/SenderEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/SenderTypeEnumEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/projection/FdrPublishReportingFlowNameProjection.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/projection/FdrPublishRevisionProjection.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/projection/Sender.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/FdrHistoryEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/FdrInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/FdrPaymentHistoryEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/FdrPaymentInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/FdrPaymentPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/FdrPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/model/AbstractReportingFlowEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/model/AbstractReportingFlowPaymentEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/projection/FdrPublishReportingFlowNameProjection.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/projection/FdrPublishRevisionProjection.java
  src/main/java/it/gov/pagopa/fdr/repository/reportingFlow/projection/Sender.java
  src/main/java/it/gov/pagopa/fdr/rest/organizations/InternalOrganizationsResource.java
  src/main/java/it/gov/pagopa/fdr/rest/organizations/OrganizationsResource.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/PspsResource.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/InternalOrganizationsService.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/OrganizationsService.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/mapper/InternalOrganizationsServiceServiceMapper.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/mapper/OrganizationsServiceServiceMapper.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
  src/main/java/it/gov/pagopa/fdr/service/psps/mapper/PspsServiceServiceMapper.java
Labels: size/large

#13 feat: Sonar
  src/main/java/it/gov/pagopa/fdr/App.java
  src/main/java/it/gov/pagopa/fdr/rest/exceptionmapper/ErrorResponse.java
  src/main/java/it/gov/pagopa/fdr/rest/exceptionmapper/ExceptionMappers.java
  src/main/java/it/gov/pagopa/fdr/rest/organizations/validation/OrganizationsValidationService.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/validation/PspsValidationService.java
  src/main/java/it/gov/pagopa/fdr/rest/validation/ListSizeValidator.java
  src/main/java/it/gov/pagopa/fdr/service/dto/ReportingFlowGetDto.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/InternalOrganizationsService.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/OrganizationsService.java
Labels: size/small

#14 Test sandbox
  docker-infra/docker-compose.yml
  docker-infra/mock/data/config.json
  docker-infra/mock/data/id.json
  docker-infra/mock/nginx/nginx.conf
  format-code.sh
  pom.xml
  src/main/java/it/gov/pagopa/fdr/AppStartup.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/validation/PspsValidationService.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/fdr/rest/psps/PspResourceTest.java
  src/test/java/it/gov/pagopa/fdr/util/MongoResource.java
  src/test/resources/mockserver.properties
  src/test/resources/mockserver/cache.json
Labels: size/large

#16 feat: SVILUPPO Nuovi FdR - JUnit Tests
  src/main/java/it/gov/pagopa/fdr/exception/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/AbstractReportingFlowEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/model/AbstractReportingFlowPaymentEntity.java
  src/main/java/it/gov/pagopa/fdr/service/dto/ReportingFlowGetDto.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
  src/main/resources/messages.properties
  src/test/java/it/gov/pagopa/fdr/Constants.java
  src/test/java/it/gov/pagopa/fdr/rest/BaseResourceTest.java
  src/test/java/it/gov/pagopa/fdr/rest/BaseUnitTestHelper.java
  src/test/java/it/gov/pagopa/fdr/rest/organizations/OrganizationResourceTest.java
  src/test/java/it/gov/pagopa/fdr/rest/psps/PspResourceTest.java
  src/test/java/it/gov/pagopa/fdr/util/AppMessageUtilTest.java
  src/test/java/it/gov/pagopa/fdr/util/TestUtil.java
Labels: size/large

#19 feat: Nod 268 junit tests
  .devops/code-review-pipelines.yml
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentHistoryEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentInsertEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPaymentPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/FdrPublishEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/fdr/QueryConstants.java
  src/main/java/it/gov/pagopa/fdr/rest/exceptionmapper/ExceptionMappers.java
  src/main/java/it/gov/pagopa/fdr/rest/psps/validation/PspsValidationService.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/InternalOrganizationsService.java
  src/main/java/it/gov/pagopa/fdr/service/organizations/OrganizationsService.java
  src/main/java/it/gov/pagopa/fdr/service/psps/PspsService.java
  src/main/java/it/gov/pagopa/fdr/util/AppConstant.java
  src/main/java/it/gov/pagopa/fdr/util/NoInternalSchemaFilter.java
  src/test/java/it/gov/pagopa/fdr/rest/BaseUnitTestHelper.java
  src/test/java/it/gov/pagopa/fdr/rest/organizations/InternalOrganizationResourceTest.java
  src/test/java/it/gov/pagopa/fdr/rest/organizations/OrganizationResourceTest.java
Labels: enhancement, size/large
