Repository pagopa/pagopa-fdr, pull requests merged in 2024-06, with the labels that each got.

#64 [NOD-905] feat: add OpEx dashboards for internal, psp and organization APIs
  .github/workflows/08_create_dashboard.yml
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_variables.tf
  .opex/env/prod/internal/backend.ini
  .opex/env/prod/internal/backend.tfvars
  .opex/env/prod/internal/config.yaml
  .opex/env/prod/internal/terraform.tfvars
  .opex/env/prod/organization/backend.ini
  .opex/env/prod/organization/backend.tfvars
  .opex/env/prod/organization/config.yaml
  .opex/env/prod/organization/terraform.tfvars
  .opex/env/prod/psp/backend.ini
  .opex/env/prod/psp/backend.tfvars
  .opex/env/prod/psp/config.yaml
  .opex/env/prod/psp/terraform.tfvars
  helm/Chart.lock
Labels: size/large, ignore-for-release

#68 fix: dynamic set for ApiConfig Cache invocation's cron
  .github/workflows/04h_deploy_with_github_runner.yml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: size/small, patch

#69 chore: Alert opex x apim v 2
  .github/workflows/08_create_dashboard.yml
  .opex/env/prod/internal/config.yaml
  .opex/env/prod/organization/config.yaml
  .opex/env/prod/psp/config.yaml
Labels: skip
