Repository pagopa/pagopa-fdr, pull requests merged in 2025-02, with the labels that each got.

#78 chore: [PAGOPA-2614] Updated slack webhook
  .github/workflows/04_release_and_deploy.yml
  .github/workflows/06_integration_test.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: size/small, skip, ignore-for-release

#79 feat: [PAGOPA-2043] defining performance tests for FdR-Fase3 application
  .github/workflows/07_performance_test.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx_dev.conf
  performance-test/nginx/nginx_uat.conf
  performance-test/run_performance_test.sh
  performance-test/src/config.json
  performance-test/src/create_flow_parallel.js
  performance-test/src/create_flow_sequential.js
  performance-test/src/dev.environment.json
  performance-test/src/environments/dev.environment.json
  performance-test/src/environments/local.environment.json
  performance-test/src/environments/uat.environment.json
  performance-test/src/happy_case_scenario.js
  performance-test/src/helpers/fdr_helper.js
  performance-test/src/helpers/payloads.json
  performance-test/src/local.environment.json
  performance-test/src/modules/client.js
  performance-test/src/modules/helper.js
  performance-test/src/modules/request_builder.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  src/main/java/it/gov/pagopa/fdr/repository/FdrFlowRepository.java
  src/main/java/it/gov/pagopa/fdr/repository/FdrPaymentRepository.java
  src/main/java/it/gov/pagopa/fdr/repository/common/Repository.java
  src/main/resources/application.properties
Labels: bug, size/large, patch

#82 feat: [PAGOPA-2644] Moving API infrastructure in repository
  .gitignore
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  infra/.terraform.lock.hcl
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/99_main.tf
  infra/99_variables.tf
  infra/env/weu-dev/backend.ini
  infra/env/weu-dev/backend.tfvars
  infra/env/weu-dev/terraform.tfvars
  infra/env/weu-prod/backend.ini
  infra/env/weu-prod/backend.tfvars
  infra/env/weu-prod/terraform.tfvars
  infra/env/weu-uat/backend.ini
  infra/env/weu-uat/backend.tfvars
  infra/env/weu-uat/terraform.tfvars
  infra/policy/_base_policy.xml.tpl
  infra/policy/org/v1/_base_policy.xml.tpl
  infra/policy/psp/v1/_base_policy.xml.tpl
  infra/terraform.sh
  openapi/openapi_internal.json
  openapi/openapi_organization.json
  openapi/openapi_psp.json
  pom.xml
  src/main/java/it/gov/pagopa/fdr/util/openapi/OpenAPIGenerator.java
Labels: bug, size/large, patch

#83 fix: resolving various problems on infrastructure
  README.md
  build-and-run.sh
  infra/04_apim_api.tf
  infra/api/internal/openapi.json
  infra/api/org/openapi.json
  infra/api/psp/openapi.json
  openapi/openapi.json
  openapi/openapi_organization.json
  openapi/openapi_psp.json
  src/main/java/it/gov/pagopa/fdr/controller/middleware/filter/RequestFilter.java
  src/main/java/it/gov/pagopa/fdr/controller/middleware/filter/ResponseFilter.java
Labels: bug, size/large, patch

#87 fix: Refactoring description for Operational error codes and I18N messages
  infra/api/internal/openapi.json
  infra/api/org/openapi.json
  infra/api/psp/openapi.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/fdr/util/common/FileUtil.java
  src/main/java/it/gov/pagopa/fdr/util/common/StringUtil.java
  src/main/java/it/gov/pagopa/fdr/util/error/enums/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/fdr/util/openapi/OpenAPIGenerator.java
  src/main/resources/messages.properties
Labels: bug

#88 chore: Refactoring API documentation
  .github/workflows/03_code_review.yml
  infra/api/internal/openapi.json
  infra/api/org/openapi.json
  infra/api/psp/openapi.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IInternalOperationsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IOrganizationsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IPspsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/ISupportController.java
  src/main/java/it/gov/pagopa/fdr/controller/model/common/Metadata.java
  src/main/java/it/gov/pagopa/fdr/controller/model/common/response/GenericResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/common/response/InfoResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/error/ErrorMessage.java
  src/main/java/it/gov/pagopa/fdr/controller/model/error/ErrorResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowByCICreated.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowByCIPublished.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowByPSP.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowBySenderAndReceiver.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/Receiver.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/Sender.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/request/CreateFlowRequest.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsBySenderAndReceiverResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsCreatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsPublishedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/SingleFlowCreatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/SingleFlowResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/Payment.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/request/AddPaymentRequest.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/request/DeletePaymentRequest.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/response/PaginatedPaymentsCreatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/response/PaginatedPaymentsResponse.java
  src/main/java/it/gov/pagopa/fdr/util/openapi/OpenAPIGenerator.java
  src/main/resources/messages.properties
Labels: bug, patch

#89 fix: Various little fixes for Release v1.1.12
  build-and-run.sh
  infra/api/internal/openapi.json
  infra/api/org/openapi.json
  infra/api/psp/openapi.json
  openapi/openapi.json
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IInternalOperationsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IOrganizationsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IPspsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/ISupportController.java
  src/main/java/it/gov/pagopa/fdr/controller/model/common/Metadata.java
  src/main/java/it/gov/pagopa/fdr/controller/model/common/response/GenericResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/common/response/InfoResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/error/ErrorMessage.java
  src/main/java/it/gov/pagopa/fdr/controller/model/error/ErrorResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowByCICreated.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowByCIPublished.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowByPSP.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/FlowBySenderAndReceiver.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/Receiver.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/Sender.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/request/CreateFlowRequest.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsBySenderAndReceiverResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsCreatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsPublishedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedFlowsResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/PaginatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/SingleFlowCreatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/flow/response/SingleFlowResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/Payment.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/request/AddPaymentRequest.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/request/DeletePaymentRequest.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/response/PaginatedPaymentsCreatedResponse.java
  src/main/java/it/gov/pagopa/fdr/controller/model/payment/response/PaginatedPaymentsResponse.java
  src/main/java/it/gov/pagopa/fdr/repository/FlowRepository.java
  src/main/java/it/gov/pagopa/fdr/util/common/FileUtil.java
  src/main/java/it/gov/pagopa/fdr/util/common/StringUtil.java
  src/main/java/it/gov/pagopa/fdr/util/error/enums/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/fdr/util/openapi/OpenAPIGenerator.java
  src/main/resources/messages.properties
  src/test/java/it/gov/pagopa/fdr/controller/internal/InternalOperationControllerTest.java
  src/test/java/it/gov/pagopa/fdr/controller/middleware/ClientGZIPDecodingInterceptorIT.java
  src/test/java/it/gov/pagopa/fdr/controller/middleware/ClientGZIPDecodingInterceptorTest.java
  src/test/java/it/gov/pagopa/fdr/controller/middleware/ExceptionMapperTest.java
  src/test/java/it/gov/pagopa/fdr/controller/organizations/OrganizationsControllerTest.java
  src/test/java/it/gov/pagopa/fdr/controller/psps/PspsControllerTest.java
  src/test/java/it/gov/pagopa/fdr/controller/support/TechnicalSupportControllerIT.java
  src/test/java/it/gov/pagopa/fdr/repository/FlowRepositoryTest.java
  src/test/java/it/gov/pagopa/fdr/repository/PaymentRepositoryIT.java
  src/test/java/it/gov/pagopa/fdr/repository/PaymentRepositoryTest.java
  src/test/java/it/gov/pagopa/fdr/repository/entity/FlowEntityIT.java
  src/test/java/it/gov/pagopa/fdr/repository/entity/FlowEntityTest.java
  src/test/java/it/gov/pagopa/fdr/service/middleware/mapper/FlowMapperTest.java
  src/test/java/it/gov/pagopa/fdr/service/middleware/mapper/TechnicalSupportMapperIT.java
  src/test/java/it/gov/pagopa/fdr/service/middleware/mapper/TechnicalSupportMapperTest.java
  src/test/java/it/gov/pagopa/fdr/test/util/AppConstantTestHelper.java
  src/test/java/it/gov/pagopa/fdr/test/util/PostgresResource.java
  src/test/java/it/gov/pagopa/fdr/test/util/TestUtil.java
  src/test/java/it/gov/pagopa/fdr/util/AppMessageUtilTest.java
  src/test/java/it/gov/pagopa/fdr/util/FileUtilTest.java
  src/test/java/it/gov/pagopa/fdr/util/StringUtilTest.java
Labels: bug, size/large, patch

#90 [PAGOPA-2609] fix: sonar project configs
  pom.xml
  src/main/docker/Dockerfile.jvm
Labels: size/small, patch

#91 [PAGOPA-2609] fix: sonar config on code review workflow
  .github/workflows/03_code_review.yml
  pom.xml
  src/main/docker/Dockerfile.jvm
Labels: size/small, skip, patch
