Repository pagopa/pagopa-fdr, pull requests merged in 2025-04, with the labels that each got.

#118 fix: new history mechanism PAGOPA-2892
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/fdr/schedule/HistoryCron.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/fdr/schedule/HistoryCronTest.java
Labels: bug, size/small, patch

#117 feat: [PAGOPA-2767] Defining OpEx dashboard for all APIs
  .github/workflows/04h_deploy_with_github_runner.yml
  .github/workflows/08_create_dashboard.yml
  .identity/03_github_environment.tf
  .identity/99_variables.tf
  .opex/env/prod/internal/config.yaml
  .opex/env/prod/organization/config.yaml
  .opex/env/prod/psp/config.yaml
  build-and-run.sh
  infra/api/internal/openapi.json
  infra/api/org/openapi.json
  infra/api/psp/openapi.json
  openapi/openapi.json
Labels: size/small, ignore-for-release

#119 chore: PAGOPA-2767-opex AZ dash & alerts
  .github/workflows/08_create_dashboard.yml
  .opex/internal/env/prod/backend.ini
  .opex/internal/env/prod/backend.tfvars
  .opex/internal/env/prod/config.yaml
  .opex/internal/env/prod/terraform.tfvars
  .opex/organization/env/prod/backend.ini
  .opex/organization/env/prod/backend.tfvars
  .opex/organization/env/prod/config.yaml
  .opex/organization/env/prod/terraform.tfvars
  .opex/psp/env/prod/backend.ini
  .opex/psp/env/prod/backend.tfvars
  .opex/psp/env/prod/config.yaml
  .opex/psp/env/prod/terraform.tfvars
Labels: size/small, ignore-for-release, patch

#115 fix: refactoring Helm file for PROD environment
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#122 chore: Fix affinity
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#123 chore: Fix-helm-nodo-type
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, patch

#125 config(HELM): Add CUSTOM_JAVA_OPTS
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  performance-test/src/test-types/constant.json
  pom.xml
Labels: size/small, patch

#126 config(HELM): CPU tuning
  helm/values-prod.yaml
Labels: size/small, patch

#128 fix: [PAGOPA-2995] Adding CUSTOM_JAVA_OPTS support on Docker image run
  .github/workflows/04_release_and_deploy.yml
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, patch

#127 config(JVM): Update memory heap
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#129 chore: bump opex dashboard action
  .github/workflows/08_create_dashboard.yml
  .opex/internal/env/prod/config.yaml
  .opex/organization/env/prod/config.yaml
  .opex/psp/env/prod/config.yaml
Labels: size/small, patch, on hold

#130 fix: resolving bug on automatic generation of endpoint-related information in OAS
  src/main/java/it/gov/pagopa/fdr/util/openapi/OpenAPIGenerator.java
Labels: documentation, size/small, skip, ignore-for-release

#132 chore: [PIDM-490] Bump helm version to 7.5.0
  helm/Chart.yaml
Labels: size/small, skip, patch
