Repository pagopa/pagopa-fdr, pull requests merged in 2025-03, with the labels that each got.

#93 fix: add missing OTEL system properties
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#94 fix: quarkus otel env variables
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#95 fix: ECS format service name, version and env
  src/main/resources/application.properties
Labels: size/small, patch

#96 fix: app name value
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/resources/application.properties
Labels: size/small, patch

#99 feat(FlowToHistoryMapper.java): implement mapper for FlowToHistoryEntity
  src/main/java/it/gov/pagopa/fdr/repository/FlowToHistoryRepository.java
  src/main/java/it/gov/pagopa/fdr/repository/entity/FlowToHistoryEntity.java
  src/main/java/it/gov/pagopa/fdr/repository/enums/FlowToHistoryStatusEnum.java
  src/main/java/it/gov/pagopa/fdr/service/FlowService.java
  src/main/java/it/gov/pagopa/fdr/service/middleware/mapper/FlowToHistoryMapper.java
Labels: patch

#98 chore: [PAGOPA-2755] Added conflicting indexes
  .gitignore
  src/main/java/it/gov/pagopa/fdr/controller/middleware/exceptionhandler/ExceptionMappers.java
  src/main/java/it/gov/pagopa/fdr/service/PaymentService.java
  src/main/java/it/gov/pagopa/fdr/util/error/exception/common/AppException.java
Labels: size/small, patch

#97 feat: inserting rate limit for payments add and payments delete Pagopa 2641
  .gitignore
  infra/04_apim_api.tf
  infra/api/internal/openapi.json
  infra/api/org/openapi.json
  infra/api/psp/openapi.json
  infra/policy/psp/v1/_base_policy_payments_add.xml.tpl
  infra/policy/psp/v1/_base_policy_payments_delete.xml.tpl
  openapi/openapi.json
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IInfoController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IInternalOperationsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IOrganizationsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IPspsController.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/ISupportController.java
Labels: enhancement, size/small, patch

#102 feat: [PAGOPA-2473] Implement workload identity & new runner
  .github/workflows/04h_deploy_with_github_runner.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#107 fix: GHA release & deploy
  .github/workflows/04_release_and_deploy.yml
Labels: size/small, skip, patch

#108 fix: GHA deploy
  .github/workflows/04_release_and_deploy.yml
  .github/workflows/04h_deploy_with_github_runner.yml
Labels: size/small, patch

#106 refactor(HistoryCron.java): improve flow locking logic
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/fdr/repository/FlowToHistoryRepository.java
  src/main/java/it/gov/pagopa/fdr/repository/entity/FlowToHistoryEntity.java
  src/main/java/it/gov/pagopa/fdr/schedule/HistoryCron.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/fdr/schedule/HistoryCronTest.java
  src/test/resources/db-init.sql
Labels: size/small, patch

#104 feat: [PAGOPA-2640] Moved fdr3 DB migration scripts from pagopa-infra
  .devops/fdr-fase3-db-migration-pipelines.yml
  .devops/fdr-fase3-db-schema-pipelines.yml
  .github/workflows/09_db_migration_with_github_runner.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_variables.tf
  src/main/resources/db/README.md
  src/main/resources/db/migration/liquibase/changelog/0/db.changelog-0.sql
  src/main/resources/db/migration/liquibase/changelog/0/deprecated.db.changelog-0.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-0.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-1.0.0.xml
  src/main/resources/db/migration/liquibase/properties/fdr.properties
Labels: size/large, skip

#105 fix: Enhancements on historicization cronjob
  helm/.helmignore
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/fdr/repository/FlowToHistoryRepository.java
  src/main/java/it/gov/pagopa/fdr/schedule/HistoryCron.java
  src/main/java/it/gov/pagopa/fdr/storage/HistoryBlobStorageService.java
  src/main/java/it/gov/pagopa/fdr/storage/middleware/FlowBlobMapper.java
  src/main/java/it/gov/pagopa/fdr/util/constant/AppConstant.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/fdr/storage/HistoryBlobStorageServiceTest.java
Labels: bug, patch

#111 fix db schema gha
  .devops/fdr-fase3-db-migration-pipelines.yml
  .devops/fdr-fase3-db-schema-pipelines.yml
  .github/workflows/10_db_schema_with_github_runner.yml
  .identity/99_variables.tf
  src/main/resources/db/migration/liquibase/changelog/0/db.init.sql
  src/main/resources/db/migration/liquibase/changelog/0/deprecated.db.changelog-0.xml
  src/main/resources/db/migration/liquibase/changelog/db.changelog-master-0.xml
Labels: size/large, patch

#112 fix: Pipeline schema grant user
  .devops/fdr-fase3-db-schema-pipelines.yml
Labels: size/small, patch

#113 fix: resolving errors on Helm files
  .github/workflows/04h_deploy_with_github_runner.yml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: bug, patch

#114 fix: Change schema pipeline env injection
  .devops/fdr-fase3-db-schema-pipelines.yml
Labels: size/small, skip

#116 fix: Updating references on endpoints
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/openapi/api_config_cache.json
Labels: size/small, patch
