Repository pagopa/pagopa-fdr, pull requests merged in 2025-01, with the labels that each got.

#74 refactor(github_scripts): improve code formatting
  .github/workflows/02_check_pr.yml
  .github/workflows/github_scripts/check_required_labels.js
  .github/workflows/github_scripts/check_size.js
  .pre-commit-config.yaml
  format-code.sh
  src/main/java/it/gov/pagopa/fdr/App.java
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IOrganizationsController.java
  src/main/java/it/gov/pagopa/fdr/util/constant/ControllerConstants.java
  src/test/java/it/gov/pagopa/fdr/controller/organizations/OrganizationResourceTest.java
  src/test/java/it/gov/pagopa/fdr/controller/psps/InternalPspResourceTest.java
  src/test/java/it/gov/pagopa/fdr/controller/psps/PspResourceTest.java
  src/test/java/it/gov/pagopa/fdr/test/util/TestUtil.java
Labels: size/large, skip, ignore-for-release

#76 chore: cleaning old connection strings, no more used
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: bug, patch

#75 feat: adding `is_latest` field for better filtering latest flows
  src/main/java/it/gov/pagopa/fdr/controller/interfaces/controller/IOrganizationsController.java
  src/main/java/it/gov/pagopa/fdr/repository/FdrFlowRepository.java
  src/main/java/it/gov/pagopa/fdr/repository/entity/flow/FdrFlowEntity.java
  src/main/java/it/gov/pagopa/fdr/service/FlowService.java
Labels: size/small, patch
